/*
 Virginia Villalobos
 COP4813.0M1
 Trip.cs

 Defines the Trip class elements
 Sets up required fields & messaging

 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace _8_1_TripLog.Models
{
    public class Trip
    {
        //Generated by the Database
        public int TripId { get; set; }


        //Generated by the user; needs validation
        [Required(ErrorMessage = "Please enter a Destination")]
        public string Destination { get; set; }

        [Required(ErrorMessage = "Please enter a Start Date")]
        public DateTime StartDate { get; set; } = DateTime.Now;

        [Required(ErrorMessage = "Please enter an End Date")]
        public DateTime EndDate { get; set; } = DateTime.Now;

        public string Accomodation { get; set; }

        public string AccomodationPhone { get; set; }

        public string AccomodationEmail { get; set; }


        public string ThingsToDo1 { get; set; }
        public string ThingsToDo2 { get; set; }
        public string ThingsToDo3 { get; set; }


        //Slug for the link config
        public string Slug => Destination?.Replace(' ', '-').ToLower() + '/';
    }
}
