// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _8_1_TripLog.Models;

namespace _8_1_TripLog.Migrations
{
    [DbContext(typeof(TripContext))]
    [Migration("20251019023836_Required")]
    partial class Required
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_8_1_TripLog.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Accomodation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccomodationEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccomodationPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThingsToDo1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThingsToDo2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThingsToDo3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TripId");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            TripId = 1,
                            Accomodation = "The Inn",
                            AccomodationEmail = "ny@hotel.com",
                            AccomodationPhone = "1231112222",
                            Destination = "New York",
                            EndDate = new DateTime(2025, 10, 18, 22, 38, 35, 624, DateTimeKind.Local).AddTicks(5753),
                            StartDate = new DateTime(2025, 10, 18, 22, 38, 35, 624, DateTimeKind.Local).AddTicks(5059),
                            ThingsToDo1 = "Statue of Liberty",
                            ThingsToDo2 = "Yankees Game",
                            ThingsToDo3 = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
